spring:
  datasource:
    url: jdbc:mysql://springboot-database.cz6ocyggys07.ap-northeast-2.rds.amazonaws.com:3306/shop
    username: admin
    password: whdro9563**
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, create-drop, validate
    show-sql: true
